### ISSUE TITLE
Email subject encoding

### ISSUE THREAD

**Issue by osysltd** [OsTicket-Reloaded/OsTicket#19]
Hello! Working in russian translation and noticed fatal errors while receiving messages about ticket status. Body is OK still subject is in ISO-8859-1 so that russian text in UTF-8 from table ost_email_template is broken.

**Comment by jasperf** [comment]
I see, you are closing all your issues. You forked the project perhaps or stopped using it?

**Comment by osysltd** [comment]
Hi Jasper,
Sorry but gave up with ticket activities in overall therefore decided to close irrelevant issues. Thank you
